# Generated by Django 2.0.5 on 2018-06-23 01:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180623_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 23, 1, 13, 47, 248856, tzinfo=utc)),
        ),
    ]
